### ISSUE TITLE
add `healthcheck` and `depends_on` 

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Create-LMS-App#19]
wait for postgres to be fully working before launching main `app` docker image 

example 

```yaml
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=king
      - POSTGRES_DB=kong
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: pg_isready -U postgres

  web:
    image: alpine
    depends_on: 
      db:
        condition: service_healthy
```
